services:
  ollama:
    image: ollama/ollama
    container_name: ollama1
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
    entrypoint: sh
    command: -c "ollama serve & sleep 5 && ollama pull gemma2:2b && tail -f /dev/null"

  app:
    build: ./app
    working_dir: /application
    volumes:
        - './app:/application'
    ports:
        - '3000:5173'
    command: >
        sh -c "
            npm install &&
            npm run dev
        "

volumes:
  ollama_data:
