services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true

  app:
    build: ./app
    working_dir: /application
    volumes:
        - './app:/application'
    ports:
        - '8080:8080'
    command: >
        sh -c "
            # npm install &&
            npm run serve
        "

volumes:
  ollama_data:
